annotations:
  category: WebsiteBuilder, CMS, Blog
apiVersion: v2
appVersion: 2.21.0
version: 1.2.3
description: A Helm chart to deploy Halo
home: https://www.halo.run
icon: https://www.halo.run/logo
maintainers:
  - email: hi@halo.run
    name: Halo Team
name: halo
sources:
  - https://github.com/halo-sigs/charts
  - https://github.com/halo-dev/halo
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.x.x
    condition: postgresql.enabled
  - name: mysql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.x.x
    condition: mysql.enabled
